/**
 * AUTO-GENERATED by scripts/gen-font-data.mjs - DO NOT EDIT BY HAND.
 * Regenerate with: node scripts/gen-font-data.mjs
 */
/** Base text encodings: character code (0-255) -> glyph name ("" = undefined). */
export declare const STANDARD_ENCODING: readonly string[];
export declare const WIN_ANSI_ENCODING: readonly string[];
export declare const MAC_ROMAN_ENCODING: readonly string[];
export declare const PDF_DOC_ENCODING: readonly string[];
export declare const SYMBOL_ENCODING: readonly string[];
export declare const ZAPF_DINGBATS_ENCODING: readonly string[];
export type BaseEncodingName = "StandardEncoding" | "WinAnsiEncoding" | "MacRomanEncoding" | "PDFDocEncoding" | "Symbol" | "ZapfDingbats";
export declare const BASE_ENCODINGS: Record<BaseEncodingName, readonly string[]>;
//# sourceMappingURL=encodings.d.ts.map