/**
 * AUTO-GENERATED by scripts/gen-font-data.mjs - DO NOT EDIT BY HAND.
 * Regenerate with: node scripts/gen-font-data.mjs
 */
/** Adobe Glyph List: glyph name -> Unicode string. */
export declare const AGL: Record<string, string>;
//# sourceMappingURL=glyph-list.d.ts.map