/**
 * AUTO-GENERATED by scripts/gen-font-data.mjs - DO NOT EDIT BY HAND.
 * Regenerate with: node scripts/gen-font-data.mjs
 */
/** base-14 AFM glyph widths (1000 units per em), keyed by glyph name. */
export declare const BASE14_WIDTHS: Record<string, Record<string, number>>;
export interface FontMetrics {
    ascent: number;
    descent: number;
    bbox: [number, number, number, number];
}
/** base-14 vertical metrics (1000 units per em). */
export declare const BASE14_METRICS: Record<string, FontMetrics>;
//# sourceMappingURL=standard-metrics.d.ts.map