import { z } from "zod";
export declare const EDIT_MODEL_VERSION: 1;
export declare const pdfEditBBoxSchema: z.ZodObject<{
    px: z.ZodNumber;
    py: z.ZodNumber;
    pw: z.ZodNumber;
    ph: z.ZodNumber;
}, z.core.$strip>;
export declare const pdfEditFontSchema: z.ZodObject<{
    name: z.ZodString;
    size: z.ZodNumber;
    bold: z.ZodDefault<z.ZodBoolean>;
    italic: z.ZodDefault<z.ZodBoolean>;
    color: z.ZodDefault<z.ZodString>;
    embeddedFontRef: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const pdfEditTextBlockSchema: z.ZodObject<{
    id: z.ZodString;
    page: z.ZodNumber;
    text: z.ZodString;
    bbox: z.ZodObject<{
        px: z.ZodNumber;
        py: z.ZodNumber;
        pw: z.ZodNumber;
        ph: z.ZodNumber;
    }, z.core.$strip>;
    font: z.ZodObject<{
        name: z.ZodString;
        size: z.ZodNumber;
        bold: z.ZodDefault<z.ZodBoolean>;
        italic: z.ZodDefault<z.ZodBoolean>;
        color: z.ZodDefault<z.ZodString>;
        embeddedFontRef: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    lineCount: z.ZodDefault<z.ZodNumber>;
    baselineY: z.ZodOptional<z.ZodNumber>;
    modified: z.ZodOptional<z.ZodBoolean>;
    deleted: z.ZodOptional<z.ZodBoolean>;
    locator: z.ZodOptional<z.ZodString>;
    overlay: z.ZodOptional<z.ZodBoolean>;
    encodableChars: z.ZodOptional<z.ZodString>;
    created: z.ZodOptional<z.ZodBoolean>;
    insertAt: z.ZodOptional<z.ZodObject<{
        px: z.ZodNumber;
        py: z.ZodNumber;
    }, z.core.$strip>>;
    originalBbox: z.ZodOptional<z.ZodObject<{
        px: z.ZodNumber;
        py: z.ZodNumber;
        pw: z.ZodNumber;
        ph: z.ZodNumber;
    }, z.core.$strip>>;
    originalFont: z.ZodOptional<z.ZodObject<{
        name: z.ZodString;
        size: z.ZodNumber;
        bold: z.ZodDefault<z.ZodBoolean>;
        italic: z.ZodDefault<z.ZodBoolean>;
        color: z.ZodDefault<z.ZodString>;
        embeddedFontRef: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    flattenToPath: z.ZodOptional<z.ZodBoolean>;
    supportsOutlines: z.ZodOptional<z.ZodBoolean>;
    segments: z.ZodOptional<z.ZodArray<z.ZodObject<{
        locator: z.ZodString;
        text: z.ZodString;
        bbox: z.ZodObject<{
            px: z.ZodNumber;
            py: z.ZodNumber;
            pw: z.ZodNumber;
            ph: z.ZodNumber;
        }, z.core.$strip>;
    }, z.core.$strip>>>;
}, z.core.$strip>;
export declare const pdfEditPageSchema: z.ZodObject<{
    number: z.ZodNumber;
    width: z.ZodNumber;
    height: z.ZodNumber;
    blocks: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        page: z.ZodNumber;
        text: z.ZodString;
        bbox: z.ZodObject<{
            px: z.ZodNumber;
            py: z.ZodNumber;
            pw: z.ZodNumber;
            ph: z.ZodNumber;
        }, z.core.$strip>;
        font: z.ZodObject<{
            name: z.ZodString;
            size: z.ZodNumber;
            bold: z.ZodDefault<z.ZodBoolean>;
            italic: z.ZodDefault<z.ZodBoolean>;
            color: z.ZodDefault<z.ZodString>;
            embeddedFontRef: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
        lineCount: z.ZodDefault<z.ZodNumber>;
        baselineY: z.ZodOptional<z.ZodNumber>;
        modified: z.ZodOptional<z.ZodBoolean>;
        deleted: z.ZodOptional<z.ZodBoolean>;
        locator: z.ZodOptional<z.ZodString>;
        overlay: z.ZodOptional<z.ZodBoolean>;
        encodableChars: z.ZodOptional<z.ZodString>;
        created: z.ZodOptional<z.ZodBoolean>;
        insertAt: z.ZodOptional<z.ZodObject<{
            px: z.ZodNumber;
            py: z.ZodNumber;
        }, z.core.$strip>>;
        originalBbox: z.ZodOptional<z.ZodObject<{
            px: z.ZodNumber;
            py: z.ZodNumber;
            pw: z.ZodNumber;
            ph: z.ZodNumber;
        }, z.core.$strip>>;
        originalFont: z.ZodOptional<z.ZodObject<{
            name: z.ZodString;
            size: z.ZodNumber;
            bold: z.ZodDefault<z.ZodBoolean>;
            italic: z.ZodDefault<z.ZodBoolean>;
            color: z.ZodDefault<z.ZodString>;
            embeddedFontRef: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        flattenToPath: z.ZodOptional<z.ZodBoolean>;
        supportsOutlines: z.ZodOptional<z.ZodBoolean>;
        segments: z.ZodOptional<z.ZodArray<z.ZodObject<{
            locator: z.ZodString;
            text: z.ZodString;
            bbox: z.ZodObject<{
                px: z.ZodNumber;
                py: z.ZodNumber;
                pw: z.ZodNumber;
                ph: z.ZodNumber;
            }, z.core.$strip>;
        }, z.core.$strip>>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export declare const pdfEditDocumentSchema: z.ZodObject<{
    version: z.ZodLiteral<1>;
    documentId: z.ZodString;
    pages: z.ZodArray<z.ZodObject<{
        number: z.ZodNumber;
        width: z.ZodNumber;
        height: z.ZodNumber;
        blocks: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            page: z.ZodNumber;
            text: z.ZodString;
            bbox: z.ZodObject<{
                px: z.ZodNumber;
                py: z.ZodNumber;
                pw: z.ZodNumber;
                ph: z.ZodNumber;
            }, z.core.$strip>;
            font: z.ZodObject<{
                name: z.ZodString;
                size: z.ZodNumber;
                bold: z.ZodDefault<z.ZodBoolean>;
                italic: z.ZodDefault<z.ZodBoolean>;
                color: z.ZodDefault<z.ZodString>;
                embeddedFontRef: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>;
            lineCount: z.ZodDefault<z.ZodNumber>;
            baselineY: z.ZodOptional<z.ZodNumber>;
            modified: z.ZodOptional<z.ZodBoolean>;
            deleted: z.ZodOptional<z.ZodBoolean>;
            locator: z.ZodOptional<z.ZodString>;
            overlay: z.ZodOptional<z.ZodBoolean>;
            encodableChars: z.ZodOptional<z.ZodString>;
            created: z.ZodOptional<z.ZodBoolean>;
            insertAt: z.ZodOptional<z.ZodObject<{
                px: z.ZodNumber;
                py: z.ZodNumber;
            }, z.core.$strip>>;
            originalBbox: z.ZodOptional<z.ZodObject<{
                px: z.ZodNumber;
                py: z.ZodNumber;
                pw: z.ZodNumber;
                ph: z.ZodNumber;
            }, z.core.$strip>>;
            originalFont: z.ZodOptional<z.ZodObject<{
                name: z.ZodString;
                size: z.ZodNumber;
                bold: z.ZodDefault<z.ZodBoolean>;
                italic: z.ZodDefault<z.ZodBoolean>;
                color: z.ZodDefault<z.ZodString>;
                embeddedFontRef: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            flattenToPath: z.ZodOptional<z.ZodBoolean>;
            supportsOutlines: z.ZodOptional<z.ZodBoolean>;
            segments: z.ZodOptional<z.ZodArray<z.ZodObject<{
                locator: z.ZodString;
                text: z.ZodString;
                bbox: z.ZodObject<{
                    px: z.ZodNumber;
                    py: z.ZodNumber;
                    pw: z.ZodNumber;
                    ph: z.ZodNumber;
                }, z.core.$strip>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export declare const pdfEditBlockPatchSchema: z.ZodObject<{
    id: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
    page: z.ZodNonOptional<z.ZodOptional<z.ZodNumber>>;
    text: z.ZodOptional<z.ZodString>;
    bbox: z.ZodOptional<z.ZodObject<{
        px: z.ZodNumber;
        py: z.ZodNumber;
        pw: z.ZodNumber;
        ph: z.ZodNumber;
    }, z.core.$strip>>;
    font: z.ZodOptional<z.ZodObject<{
        name: z.ZodString;
        size: z.ZodNumber;
        bold: z.ZodDefault<z.ZodBoolean>;
        italic: z.ZodDefault<z.ZodBoolean>;
        color: z.ZodDefault<z.ZodString>;
        embeddedFontRef: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    lineCount: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    baselineY: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    modified: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    deleted: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    locator: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    overlay: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    encodableChars: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    created: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    insertAt: z.ZodOptional<z.ZodOptional<z.ZodObject<{
        px: z.ZodNumber;
        py: z.ZodNumber;
    }, z.core.$strip>>>;
    originalBbox: z.ZodOptional<z.ZodOptional<z.ZodObject<{
        px: z.ZodNumber;
        py: z.ZodNumber;
        pw: z.ZodNumber;
        ph: z.ZodNumber;
    }, z.core.$strip>>>;
    originalFont: z.ZodOptional<z.ZodOptional<z.ZodObject<{
        name: z.ZodString;
        size: z.ZodNumber;
        bold: z.ZodDefault<z.ZodBoolean>;
        italic: z.ZodDefault<z.ZodBoolean>;
        color: z.ZodDefault<z.ZodString>;
        embeddedFontRef: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>>;
    flattenToPath: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    supportsOutlines: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    segments: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodObject<{
        locator: z.ZodString;
        text: z.ZodString;
        bbox: z.ZodObject<{
            px: z.ZodNumber;
            py: z.ZodNumber;
            pw: z.ZodNumber;
            ph: z.ZodNumber;
        }, z.core.$strip>;
    }, z.core.$strip>>>>;
}, z.core.$strip>;
export declare const pdfEditPatchSchema: z.ZodObject<{
    documentId: z.ZodString;
    blocks: z.ZodArray<z.ZodObject<{
        id: z.ZodNonOptional<z.ZodOptional<z.ZodString>>;
        page: z.ZodNonOptional<z.ZodOptional<z.ZodNumber>>;
        text: z.ZodOptional<z.ZodString>;
        bbox: z.ZodOptional<z.ZodObject<{
            px: z.ZodNumber;
            py: z.ZodNumber;
            pw: z.ZodNumber;
            ph: z.ZodNumber;
        }, z.core.$strip>>;
        font: z.ZodOptional<z.ZodObject<{
            name: z.ZodString;
            size: z.ZodNumber;
            bold: z.ZodDefault<z.ZodBoolean>;
            italic: z.ZodDefault<z.ZodBoolean>;
            color: z.ZodDefault<z.ZodString>;
            embeddedFontRef: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        lineCount: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
        baselineY: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
        modified: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
        deleted: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
        locator: z.ZodOptional<z.ZodOptional<z.ZodString>>;
        overlay: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
        encodableChars: z.ZodOptional<z.ZodOptional<z.ZodString>>;
        created: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
        insertAt: z.ZodOptional<z.ZodOptional<z.ZodObject<{
            px: z.ZodNumber;
            py: z.ZodNumber;
        }, z.core.$strip>>>;
        originalBbox: z.ZodOptional<z.ZodOptional<z.ZodObject<{
            px: z.ZodNumber;
            py: z.ZodNumber;
            pw: z.ZodNumber;
            ph: z.ZodNumber;
        }, z.core.$strip>>>;
        originalFont: z.ZodOptional<z.ZodOptional<z.ZodObject<{
            name: z.ZodString;
            size: z.ZodNumber;
            bold: z.ZodDefault<z.ZodBoolean>;
            italic: z.ZodDefault<z.ZodBoolean>;
            color: z.ZodDefault<z.ZodString>;
            embeddedFontRef: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>>;
        flattenToPath: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
        supportsOutlines: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
        segments: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodObject<{
            locator: z.ZodString;
            text: z.ZodString;
            bbox: z.ZodObject<{
                px: z.ZodNumber;
                py: z.ZodNumber;
                pw: z.ZodNumber;
                ph: z.ZodNumber;
            }, z.core.$strip>;
        }, z.core.$strip>>>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type PdfEditBBox = z.infer<typeof pdfEditBBoxSchema>;
export type PdfEditFont = z.infer<typeof pdfEditFontSchema>;
export type PdfEditTextBlock = z.infer<typeof pdfEditTextBlockSchema>;
export type PdfEditPage = z.infer<typeof pdfEditPageSchema>;
export type PdfEditDocument = z.infer<typeof pdfEditDocumentSchema>;
export type PdfEditBlockPatch = z.infer<typeof pdfEditBlockPatchSchema>;
export type PdfEditPatch = z.infer<typeof pdfEditPatchSchema>;
export declare function parsePdfEditDocument(data: unknown): PdfEditDocument;
export declare function parsePdfEditPatch(data: unknown): PdfEditPatch;
export declare function buildPdfEditPatch(document: PdfEditDocument, blocks: PdfEditTextBlock[]): PdfEditPatch;
//# sourceMappingURL=edit-model.d.ts.map