export declare function initPdfJs(): Promise<{
    default: typeof import("pdfjs-dist");
    AbortException: typeof import("pdfjs-dist").AbortException;
    AnnotationEditorLayer: typeof import("pdfjs-dist").AnnotationEditorLayer;
    AnnotationEditorParamsType: typeof import("pdfjs-dist").AnnotationEditorParamsType;
    AnnotationEditorType: typeof import("pdfjs-dist").AnnotationEditorType;
    AnnotationEditorUIManager: typeof import("pdfjs-dist").AnnotationEditorUIManager;
    AnnotationLayer: typeof import("pdfjs-dist").AnnotationLayer;
    AnnotationMode: typeof import("pdfjs-dist").AnnotationMode;
    AnnotationType: typeof import("pdfjs-dist").AnnotationType;
    applyOpacity: typeof import("pdfjs-dist").applyOpacity;
    build: string;
    ColorPicker: typeof import("pdfjs-dist").ColorPicker;
    createValidAbsoluteUrl: typeof import("pdfjs-dist").createValidAbsoluteUrl;
    CSSConstants: typeof import("pdfjs-dist").CSSConstants;
    DOMSVGFactory: typeof import("pdfjs-dist").DOMSVGFactory;
    DrawLayer: typeof import("pdfjs-dist").DrawLayer;
    FeatureTest: typeof import("pdfjs-dist").FeatureTest;
    fetchData: typeof import("pdfjs-dist").fetchData;
    findContrastColor: typeof import("pdfjs-dist").findContrastColor;
    getDocument: typeof import("pdfjs-dist").getDocument;
    getFilenameFromUrl: typeof import("pdfjs-dist").getFilenameFromUrl;
    getPdfFilenameFromUrl: typeof import("pdfjs-dist").getPdfFilenameFromUrl;
    getRGB: typeof import("pdfjs-dist").getRGB;
    getRGBA: typeof import("pdfjs-dist").getRGBA;
    getUuid: typeof import("pdfjs-dist").getUuid;
    GlobalWorkerOptions: typeof import("pdfjs-dist").GlobalWorkerOptions;
    ImageKind: typeof import("pdfjs-dist").ImageKind;
    InvalidPDFException: typeof import("pdfjs-dist").InvalidPDFException;
    isDataScheme: typeof import("pdfjs-dist").isDataScheme;
    isPdfFile: typeof import("pdfjs-dist").isPdfFile;
    isValidExplicitDest: (dest?: any) => boolean;
    makeArr: typeof import("pdfjs-dist").makeArr;
    makeMap: typeof import("pdfjs-dist").makeMap;
    makeObj: typeof import("pdfjs-dist").makeObj;
    MathClamp: typeof import("pdfjs-dist").MathClamp;
    noContextMenu: typeof import("pdfjs-dist").noContextMenu;
    normalizeUnicode: typeof import("pdfjs-dist").normalizeUnicode;
    OPS: typeof import("pdfjs-dist").OPS;
    OutputScale: typeof import("pdfjs-dist").OutputScale;
    PasswordException: typeof import("pdfjs-dist").PasswordException;
    PasswordResponses: typeof import("pdfjs-dist").PasswordResponses;
    PDFDataRangeTransport: typeof import("pdfjs-dist").PDFDataRangeTransport;
    PDFDateString: typeof import("pdfjs-dist").PDFDateString;
    PDFWorker: typeof import("pdfjs-dist").PDFWorker;
    PermissionFlag: typeof import("pdfjs-dist").PermissionFlag;
    PixelsPerInch: typeof import("pdfjs-dist").PixelsPerInch;
    RenderingCancelledException: typeof import("pdfjs-dist").RenderingCancelledException;
    renderRichText: typeof import("pdfjs-dist").renderRichText;
    ResponseException: typeof import("pdfjs-dist").ResponseException;
    setLayerDimensions: typeof import("pdfjs-dist").setLayerDimensions;
    shadow: typeof import("pdfjs-dist").shadow;
    SignatureExtractor: typeof import("pdfjs-dist").SignatureExtractor;
    stopEvent: typeof import("pdfjs-dist").stopEvent;
    SupportedImageMimeTypes: string[];
    TextLayer: typeof import("pdfjs-dist").TextLayer;
    TextLayerImages: typeof import("pdfjs-dist").TextLayerImages;
    TouchManager: typeof import("pdfjs-dist").TouchManager;
    updateUrlHash: typeof import("pdfjs-dist").updateUrlHash;
    Util: typeof import("pdfjs-dist").Util;
    VerbosityLevel: typeof import("pdfjs-dist").VerbosityLevel;
    version: string;
    XfaLayer: typeof import("pdfjs-dist").XfaLayer;
}>;
export declare function loadPdfJsDocument(file: File): Promise<import("pdfjs-dist/types/src/display/api").PDFDocumentProxy>;
//# sourceMappingURL=pdfjs-config.d.ts.map